spring:
  application:
    name: user-service


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9102/eureka}
  instance:
    prefer-ip-address: true